service: instagram-tool-backend
frameworkVersion: '3'

provider:
  name: aws
  runtime: python3.9
  region: ap-south-1
  profile: default
  
  httpApi:
    cors: true
    authorizers:
      jwtAuthorizer:
        type: request
        functionName: jwtAuthorizer
        identitySource: "$request.header.Authorization"

  iam:
    role:
      statements:
        - Effect: "Allow"
          Action: ["dynamodb:*"]
          Resource: "arn:aws:dynamodb:${aws:region}:${aws:accountId}:table/${self:custom.cacheTableName}"
        - Effect: "Allow"
          Action: "secretsmanager:GetSecretValue"
          Resource: "arn:aws:secretsmanager:ap-south-1:056200465083:secret:instagram-tool-secrets-*"

plugins:
  - serverless-python-requirements

custom:
  cacheTableName: instagram-tool-final-table
  pythonRequirements:
    dockerizePip: non-linux
    layer: true
    noDeploy: [boto3, botocore]
      
functions:
  # Token generate karne wala function (public, no authorizer)
  generateToken:
    handler: auth_handler.generate_token
    layers:
      - Ref: PythonRequirementsLambdaLayer
    environment:
      SECRET_NAME: "instagram-tool-secrets"
    events:
      - httpApi:
          path: /v1/auth/token
          method: post

  # Profile fetch karne wala function (private, authorizer ke saath)
  getProfile:
    handler: handler.get_instagram_profile
    environment:
      CACHE_TABLE_NAME: ${self:custom.cacheTableName}
      CACHE_TTL_SECONDS: 1500
      SECRET_NAME: "instagram-tool-secrets"
    layers:
      - Ref: PythonRequirementsLambdaLayer
    events:
      - httpApi:
          path: /v1/profile
          method: get
          authorizer:
            name: jwtAuthorizer # Authorizer yahan lagna chahiye

  # Authorizer function
  jwtAuthorizer:
    handler: auth_handler.authorize
    layers:
      - Ref: PythonRequirementsLambdaLayer
    environment:
      SECRET_NAME: "instagram-tool-secrets"

resources:
  Resources:
    CacheTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: ${self:custom.cacheTableName}
        AttributeDefinitions: [{AttributeName: username, AttributeType: S}]
        KeySchema: [{AttributeName: username, KeyType: HASH}]
        TimeToLiveSpecification: {AttributeName: ttl, Enabled: true}
        BillingMode: PAY_PER_REQUEST