service: instagram-tool-backend
frameworkVersion: '3'

provider:
  name: aws
  runtime: python3.9
  region: ap-south-1
  profile: default
  
  httpApi:
    cors: true
    authorizers:
      jwtAuthorizer:
        type: request
        functionName: jwtAuthorizer
        identitySource: "$request.header.Authorization"

  iam:
    role:
      statements:
        - Effect: "Allow"
          Action: ["dynamodb:*"]
          Resource: "arn:aws:dynamodb:${aws:region}:${aws:accountId}:table/${self:custom.cacheTableName}"
        - Effect: "Allow"
          Action: "secretsmanager:GetSecretValue"
          Resource: "arn:aws:secretsmanager:ap-south-1:056200465083:secret:instagram-tool-secrets-*"

plugins:
  - serverless-python-requirements

custom:
  cacheTableName: instagram-tool-cache-final # Naya naam taaki conflict na ho
  pythonRequirements:
    dockerizePip: non-linux
    # Hum sirf boto3 ko exclude karenge
    noDeploy:
      - boto3
      - botocore
      
functions:
  generateToken:
    handler: auth_handler.generate_token
    events:
      - httpApi: { path: /v1/auth/token, method: post }
          
  getProfile:
    handler: handler.get_instagram_profile
    environment:
      CACHE_TABLE_NAME: ${self:custom.cacheTableName}
      CACHE_TTL_SECONDS: 2400 # 40 minutes
    events:
      - httpApi:
          path: /v1/profile
          method: get
          authorizer:
            name: jwtAuthorizer

  getContent:
    handler: handler.get_content_data
    environment:
      CACHE_TABLE_NAME: ${self:custom.cacheTableName}
      CACHE_TTL_SECONDS: 2400
    events:
      - httpApi:
          path: /v1/content
          method: get
          authorizer:
            name: jwtAuthorizer

  jwtAuthorizer:
    handler: auth_handler.authorize

resources:
  Resources:
    CacheTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: ${self:custom.cacheTableName}
        # Key ko 'id' banaya gaya hai, jo profile ke liye username aur content ke liye post id ho sakti hai
        AttributeDefinitions: [{AttributeName: id, AttributeType: S}]
        KeySchema: [{AttributeName: id, KeyType: HASH}]
        TimeToLiveSpecification: {AttributeName: ttl, Enabled: true}
        BillingMode: PAY_PER_REQUEST